#+TITLE: yank

  A Firefox extension to copy current tab URL to clipboard, formatted in one of
  these supported markup languages:

** Usage
   By default this plugin binds ~ctrl+y~ to copy URL as org-mode. To change this
   open up the options page, either from a ~about:addons~ or by clicking the addon
   icon in the toolbar

*** Shortcut keys
   Currently allowed keybinds are any alphanumeric key and/or any combination of
   ctrl/alt/shift

*** Supported formats
    Yank currently supports these markup languages:

   - [[http://orgmode.org/][Org-mode]]
   - [[https://daringfireball.net/projects/markdown/][Markdown]]
   - [[https://github.com/textile][Textile]]
   - [[http://asciidoc.org/][AsciiDoc]]
   - [[http://docutils.sourceforge.net/rst.html][reStructuredText]]
   - [[https://www.w3.org/html/][HTML]]

   I wrote this plugin solely for org-mode, and just added the remaining formats
   since it required very little once the code surrounding it actually worked.
   Reason I mention this is that I don't actively use the other formats, so aside
   from markdown I can't say with certainty that the plugin handles it correctly.
   Please open an issue if there is a problem, or any other format is desired.

** Development
   1. Clone this repository
   #+BEGIN_EXAMPLE
   $ git clone https://github.com/roosta/yank
   $ cd yank
   #+END_EXAMPLE

   2. To get a development version going, open up a terminal and run:
   #+BEGIN_EXAMPLE
   $ lein fig
   #+END_EXAMPLE

   3. Open up a second terminal and run:
   #+BEGIN_EXAMPLE
   $ lein content
   #+END_EXAMPLE

   This will build everything, and give you a REPL connected to the options
   namespace. Open up Firefox and goto ~about:debugging~ -> Load Temporary Add-on
   -> browse to: ~[project-root]/resources/dev/manifest.json~

** Bugs
   There are very likely bugs contained in this plugin. I'm actively using it
   myself, and fixing stuff as I find it, but any submitted issue is appreciated.

** Other projects
*** chromex-sample

    https://github.com/binaryage/chromex-sample

    Borrowed a fair bit from this project's tooling. Never coded a web-extension
    plugin before and this repo really helped me out

*** chrome-shortkeys

    https://github.com/mikecrittenden/chrome-shortkeys

    Inspired how to handle binding custom keys, before I stumbled on this plugin
    I really had no idea how to go about doing this.

*** Mousetrap

    https://craig.is/killing/mice

    Using this neat library to bind the custom shortcut keys.

*** Figwheel

    https://github.com/bhauman/lein-figwheel

    Plugin used to hotload source code when developing

*** Other plugins
    1. [[https://addons.mozilla.org/en-US/firefox/addon/copy-as-org-mode/?src=search][Copy as Org-mode]]
    2. [[https://addons.mozilla.org/en-US/firefox/addon/org-capture/?src=search][Org Capture]]

    These plugins looks nice, I would have used one of them, but they were
    either to complicated or didn't support custom shortcuts.

** License

Copyright © 2017 Daniel Berg

Distributed under the Eclipse Public License either version 1.0 or (at
your option) any later version.
